version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-compose
    environment:
      SA_PASSWORD: admin123!
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"

  mysql:
    image: mysql:8.0
    container_name: mysql-compose
    environment:
      MYSQL_ROOT_PASSWORD: admin123!
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"

  postgres:
    image: postgres:13
    container_name: postgres-compose
    environment:
      POSTGRES_PASSWORD: admin123!
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
