version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: myuser
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  sqlite:
    image: tiangolo/sqlite-web:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./sqlite:/app/data
